apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: huztsgfxr-go 
  janus-idp.io/tekton: huztsgfxr-go
  backstage.io/kubernetes-id: huztsgfxr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: huztsgfxr-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml